# Generated by Django 4.1.2 on 2022-11-01 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_care_app', '0002_patients'),
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terms', models.BooleanField(verbose_name='You got this responsability')),
                ('user', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('option', models.CharField(choices=[('It heppened to me', 'It heppened to me'), ('It was already like that', 'It was already like that')], max_length=100)),
                ('reason', models.CharField(choices=[('Delete patient', 'Delete patient'), ('System problems', 'System problems'), ('Others', 'Others')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('situation', models.CharField(choices=[('Done', 'Done'), ('Pending', 'Pending')], default='Pending', max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='patients',
            name='note',
            field=models.TextField(blank=True),
        ),
    ]
